from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from app.api.deps import get_current_user_id
from app.db.session import get_db
from app.schemas.agent import (
    OutfitRecommendationRequest,
    OutfitRecommendationResponse,
)
from app.services.agent_llm_service import AgentConfigurationError
from app.services.conversation_store import JsonlConversationStore
from app.services.outfit_agent_service import OutfitRecommendationAgent

router = APIRouter(prefix="/agent", tags=["agent"])


@router.post(
    "/outfit-recommendation",
    response_model=OutfitRecommendationResponse,
)
def recommend_outfit(
    body: OutfitRecommendationRequest,
    db: Session = Depends(get_db),
    user_id=Depends(get_current_user_id),
):
    """Runs the outfit recommendation Agent for the authenticated user.

    Args:
        body: Natural-language recommendation request and optional filters.
        db: Request-scoped database session.
        user_id: Authenticated user identifier resolved from the bearer token.

    Returns:
        Structured recommendation response generated by the LangGraph Agent.

    Raises:
        HTTPException: Returns 503 when the LLM provider is not configured.
    """
    # Configuration failures are infrastructure problems, not user request
    # errors, so expose them as a clear service-unavailable response.
    try:
        data = OutfitRecommendationAgent(
            conversation_store=JsonlConversationStore(),
        ).run(db, user_id=user_id, request=body)
    except AgentConfigurationError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc

    # The service returns the response payload only; the route wraps it in the
    # public API envelope to keep schema ownership at the API boundary.
    return OutfitRecommendationResponse(data=data)
