from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session

from app.api.deps import get_current_user_id
from app.core.config import settings
from app.db.session import get_db
from app.schemas.agent import (
    AgentChatHistoryResponse,
    AgentChatRequest,
    AgentChatResponse,
    OutfitRecommendationRequest,
    OutfitRecommendationResponse,
)
from app.services.agent_llm_service import AgentConfigurationError
from app.services.conversation_store import JsonlConversationStore
from app.services.outfit_agent_service import OutfitRecommendationAgent

router = APIRouter(prefix="/agent", tags=["agent"])


@router.post(
    "/outfit-recommendation",
    response_model=OutfitRecommendationResponse,
)
def recommend_outfit(
    body: OutfitRecommendationRequest,
    db: Session = Depends(get_db),
    user_id=Depends(get_current_user_id),
):
    """Runs the outfit recommendation Agent for the authenticated user.

    Args:
        body: Natural-language recommendation request and optional filters.
        db: Request-scoped database session.
        user_id: Authenticated user identifier resolved from the bearer token.

    Returns:
        Structured recommendation response generated by the LangGraph Agent.

    Raises:
        HTTPException: Returns 503 when the LLM provider is not configured.
    """
    # Configuration failures are infrastructure problems, not user request
    # errors, so expose them as a clear service-unavailable response.
    try:
        data = OutfitRecommendationAgent(
            conversation_store=JsonlConversationStore(),
        ).run(db, user_id=user_id, request=body)
    except AgentConfigurationError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc

    # The service returns the response payload only; the route wraps it in the
    # public API envelope to keep schema ownership at the API boundary.
    return OutfitRecommendationResponse(data=data)


@router.get(
    "/chat/history",
    response_model=AgentChatHistoryResponse,
)
def get_chat_history(
    user_id=Depends(get_current_user_id),
    limit: int = Query(
        default=settings.AGENT_CONVERSATION_HISTORY_LIMIT,
        ge=1,
        le=50,
    ),
):
    """Loads recent Agent chat turns for the authenticated user."""
    store = JsonlConversationStore()
    try:
        data = store.load_context(user_id=user_id, limit=limit)
    except OSError:
        data = {
            "conversationId": f"user:{user_id}",
            "recentTurns": [],
            "lastRecommendation": None,
        }
    return AgentChatHistoryResponse(data=data)


@router.post(
    "/chat",
    response_model=AgentChatResponse,
)
def chat_outfit_agent(
    body: AgentChatRequest,
    db: Session = Depends(get_db),
    user_id=Depends(get_current_user_id),
):
    """Runs one conversational outfit Agent turn for the authenticated user.

    Args:
        body: User message, optional conversation id, and optional filters.
        db: Request-scoped database session.
        user_id: Authenticated user identifier resolved from the bearer token.

    Returns:
        Structured chat response with the current recommendation payload.

    Raises:
        HTTPException: Returns 503 when the LLM provider is not configured.
    """
    try:
        data = OutfitRecommendationAgent(
            conversation_store=JsonlConversationStore(),
        ).run_chat(db, user_id=user_id, request=body)
    except AgentConfigurationError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc

    return AgentChatResponse(data=data)
