import json
from datetime import date
from typing import Any, Literal, TypedDict
from uuid import UUID

from langgraph.graph import END, START, StateGraph
from sqlalchemy.orm import Session

from app.core.config import settings
from app.models.clothing_item import ClothingItem
from app.schemas.agent import AgentToolResult, OutfitRecommendationRequest
from app.services.agent_llm_service import (
    AgentConfigurationError,
    AgentLLMError,
    OpenAICompatibleChatClient,
)
from app.services.clothing_taxonomy import (
    CATEGORY_TO_PREVIEW_GARMENT_CATEGORY,
    get_clothing_taxonomy,
)
from app.services.conversation_store import (
    ConversationStore,
    compact_assistant_result,
)
from app.services.outfit_agent_tools import (
    OutfitAgentToolExecutor,
    valid_tag_values_by_key,
)
from app.services.weather_client import WeatherClient, WeatherClientError

MAX_TOOL_ROUNDS = 8


class OutfitAgentState(TypedDict, total=False):
    """Shared state passed between LangGraph outfit recommendation nodes."""

    db: Session
    user_id: UUID
    request: OutfitRecommendationRequest
    tools: dict[str, AgentToolResult]
    conversation_context: dict[str, Any]
    interpreted_context: dict[str, Any]
    taxonomy: dict[str, Any]
    weather_context: dict[str, Any]
    wardrobe_items: list[dict[str, Any]]
    tool_cache: dict[str, AgentToolResult]
    recommendation: dict[str, Any]
    preview: AgentToolResult
    final: dict[str, Any]


class OutfitRecommendationAgent:
    """LangGraph workflow for outfit recommendation.

    The workflow is intentionally controlled instead of being a fully open
    ReAct loop. Business-critical tool ordering stays deterministic, while the
    LLM is used for the recommendation decision itself.
    """

    def __init__(
        self,
        llm: OpenAICompatibleChatClient | None = None,
        weather_client: WeatherClient | None = None,
        conversation_store: ConversationStore | None = None,
    ) -> None:
        """Initializes the Agent and compiles its LangGraph workflow.

        Args:
            llm: Optional chat client override used by tests or alternate
                OpenAI-compatible providers.
            weather_client: Optional weather client override. When None a real
                WeatherClient is used, which fetches live Open-Meteo data.
            conversation_store: Optional conversation history store. When None,
                the Agent runs statelessly.
        """
        self.llm = llm or OpenAICompatibleChatClient()
        self.weather_client = weather_client or WeatherClient()
        self.conversation_store = conversation_store
        self.graph = self._build_graph()

    def run(
        self,
        db: Session,
        *,
        user_id: UUID,
        request: OutfitRecommendationRequest,
    ) -> dict[str, Any]:
        """Runs the outfit Agent for one authenticated user request.

        Args:
            db: Database session used by tool nodes.
            user_id: Authenticated user identifier.
            request: User request and optional retrieval filters.

        Returns:
            Final structured recommendation payload.

        Raises:
            AgentConfigurationError: If the LLM provider configuration is
                missing before the graph starts.
        """
        self.llm.ensure_configured()
        conversation_context = self._load_conversation_context(user_id)

        # Seed the graph state with backend-only objects. These are never
        # generated by the model, which keeps tool execution trusted.
        final_state = self.graph.invoke(
            {
                "db": db,
                "user_id": user_id,
                "request": request,
                "tools": {},
                "conversation_context": conversation_context,
            }
        )
        final = final_state["final"]
        self._save_conversation_turn(
            user_id=user_id,
            user_message=request.message,
            final=final,
        )
        return final

    def _load_conversation_context(self, user_id: UUID) -> dict[str, Any]:
        """Loads prompt-safe conversation history for one user.

        Args:
            user_id: Authenticated user identifier.

        Returns:
            Conversation context, or an empty context when no store is present.
        """
        if self.conversation_store is None:
            return _empty_conversation_context(user_id)

        # Conversation history is useful context, not a hard dependency. If the
        # local JSONL file is temporarily unreadable, recommendation still runs.
        try:
            return self.conversation_store.load_context(
                user_id=user_id,
                limit=settings.AGENT_CONVERSATION_HISTORY_LIMIT,
            )
        except OSError:
            return _empty_conversation_context(user_id)

    def _save_conversation_turn(
        self,
        *,
        user_id: UUID,
        user_message: str,
        final: dict[str, Any],
    ) -> None:
        """Persists the current user turn when a store is configured.

        Args:
            user_id: Authenticated user identifier.
            user_message: Current user message.
            final: Final Agent response payload.
        """
        if self.conversation_store is None:
            return

        # A failed append should not hide a usable recommendation from the API
        # caller. The returned final payload still carries conversationId.
        try:
            self.conversation_store.append_turn(
                user_id=user_id,
                user_message=user_message,
                assistant_result=compact_assistant_result(final),
            )
        except OSError:
            return

    def _build_graph(self):
        """Builds the controlled LangGraph recommendation workflow.

        Returns:
            A compiled LangGraph workflow ready to invoke.
        """
        # Register the outer business workflow as graph nodes. The recommendation
        # node contains its own LLM tool loop, while weather/taxonomy/preview
        # remain deterministic graph stages.
        workflow = StateGraph(OutfitAgentState)
        workflow.add_node("understand_request", self._understand_request)
        workflow.add_node("get_weather", self._get_weather)
        workflow.add_node("get_clothing_taxonomy", self._get_clothing_taxonomy)
        workflow.add_node("outfit_agent_loop", self._outfit_agent_loop)
        workflow.add_node("generate_outfit_preview", self._generate_outfit_preview)
        workflow.add_node("final_response", self._final_response)

        workflow.add_edge(START, "understand_request")
        workflow.add_edge("understand_request", "get_weather")
        workflow.add_edge("get_weather", "get_clothing_taxonomy")
        workflow.add_edge("get_clothing_taxonomy", "outfit_agent_loop")

        # Preview is conditional because the first JSON-only endpoint cannot
        # upload a person image. The graph still models the node so later work
        # can connect the real preview API without reshaping the workflow.
        workflow.add_conditional_edges(
            "outfit_agent_loop",
            self._preview_branch,
            {
                "preview": "generate_outfit_preview",
                "final": "final_response",
            },
        )
        workflow.add_edge("generate_outfit_preview", "final_response")
        workflow.add_edge("final_response", END)
        return workflow.compile()

    def _understand_request(self, state: OutfitAgentState) -> dict[str, Any]:
        """Extracts structured request context from the user's message.

        Args:
            state: Current LangGraph state.

        Returns:
            Partial state update containing interpreted request context and a
            tool-like trace entry.
        """
        request = state["request"]
        tools = dict(state.get("tools", {}))

        # Explicit API fields are trusted more than text extraction. The LLM
        # node fills gaps such as "明天" in message when targetDate was omitted.
        fallback_context = _request_context_from_explicit_fields(request)
        if not hasattr(self.llm, "complete_json"):
            result = AgentToolResult(
                status="skipped",
                errorCode="REQUEST_UNDERSTANDING_UNAVAILABLE",
                retryable=False,
                messageForAgent=(
                    "The configured test LLM has no complete_json method. Use "
                    "only explicit request fields for date and location."
                ),
                data=fallback_context,
            )
            tools["understand_request"] = result
            return {"tools": tools, "interpreted_context": fallback_context}

        try:
            raw_context = self.llm.complete_json(
                self._request_understanding_messages(
                    request,
                    state.get("conversation_context", {}),
                )
            )
            interpreted_context = _normalize_interpreted_context(
                raw_context,
                fallback_context,
            )
            result = AgentToolResult(
                status="success",
                data=interpreted_context,
                messageForAgent=(
                    "Structured user request context extracted. Prefer "
                    "explicit API fields when they conflict with extracted "
                    "message fields."
                ),
            )
        except (AgentConfigurationError, AgentLLMError, ValueError) as exc:
            interpreted_context = fallback_context
            result = AgentToolResult(
                status="failed",
                errorCode="REQUEST_UNDERSTANDING_FAILED",
                retryable=True,
                messageForAgent=(
                    f"Request understanding failed: {exc}. Continue with "
                    "explicit request fields only."
                ),
                messageForUser="暂时无法解析自然语言里的日期或地点，将使用已提供的请求字段。",
                data=fallback_context,
            )

        tools["understand_request"] = result
        return {"tools": tools, "interpreted_context": interpreted_context}

    def _request_understanding_messages(
        self,
        request: OutfitRecommendationRequest,
        conversation_context: dict[str, Any] | None = None,
    ) -> list[dict[str, Any]]:
        """Builds messages for structured request understanding.

        Args:
            request: Public outfit recommendation request.
            conversation_context: Recent turns from the current user's single
                conversation.

        Returns:
            OpenAI-compatible message list for extracting request context.
        """
        payload = {
            "currentDate": date.today().isoformat(),
            "request": request.model_dump(mode="json", by_alias=True),
            "conversationContext": conversation_context or {},
            "responseSchema": {
                "intent": "new_outfit|revise_outfit|ask_question|other",
                "targetDate": "YYYY-MM-DD|null",
                "city": "string|null",
                "weatherRequired": "boolean",
                "occasion": "string|null",
                "styleIntent": "string|null",
                "carryOverPreviousOutfit": "boolean",
                "revisionRequest": {
                    "slot": "top|bottom|shoes|outerwear|accessory|null",
                    "instruction": "string|null",
                },
                "userConstraints": ["string"],
            },
        }

        # This node is intentionally extraction-only. The recommendation model
        # still makes outfit decisions later after weather and wardrobe tools run.
        return [
            {
                "role": "system",
                "content": (
                    "You extract structured context for an outfit Agent. "
                    "Resolve relative dates in the user's message using "
                    "currentDate. For example, 明天 or tomorrow means currentDate + 1 day "
                    "Return only a raw JSON object matching responseSchema. "
                    "Do not recommend clothes and do not invent a city when the "
                    "request does not mention one. If the user asks to modify "
                    "the previous outfit, set intent=revise_outfit and "
                    "carryOverPreviousOutfit=true."
                ),
            },
            {
                "role": "user",
                "content": _json_dumps(payload),
            },
        ]

    def _get_weather(self, state: OutfitAgentState) -> dict[str, Any]:
        """Fetches real weather for the request location and updates state.

        Priority: GPS coordinates → city geocoding → skip. When the location
        or date is missing, or the provider fails, this node produces a
        degraded result so the model still knows not to invent weather facts.

        Args:
            state: Current LangGraph state.

        Returns:
            Partial state update containing weather context and tool result.
        """
        request = state["request"]
        interpreted_context = state.get("interpreted_context", {})
        interpreted_date = _parse_interpreted_date(
            interpreted_context.get("targetDate")
        )
        target_date = request.target_date or interpreted_date or date.today()

        # A partial coordinate pair is treated as "no location" so callers
        # must supply both latitude and longitude together.
        has_coords = (
            request.latitude is not None and request.longitude is not None
        )
        interpreted_city = interpreted_context.get("city")
        city = request.city or (
            interpreted_city if isinstance(interpreted_city, str) else None
        )
        has_city = bool(city)
        tools = dict(state.get("tools", {}))

        # ── no location at all ────────────────────────────────────────
        if not has_coords and not has_city:
            data: dict[str, Any] = {
                "city": None,
                "targetDate": target_date.isoformat(),
                "note": (
                    "No city or GPS coordinates were provided. Infer weather "
                    "only from the user's message and date if present."
                ),
            }
            result = AgentToolResult(
                status="skipped",
                errorCode="LOCATION_NOT_PROVIDED",
                retryable=False,
                messageForAgent=(
                    "No city or coordinates provided. Do not invent exact "
                    "temperature, precipitation, or wind values."
                ),
                messageForUser="未提供城市或GPS坐标信息，暂不获取实时天气。",
                data=data,
            )
            tools["get_weather"] = result
            return {"tools": tools, "weather_context": data}

        # ── fetch real forecast ───────────────────────────────────────
        try:
            forecast = self.weather_client.fetch_forecast(
                target_date,
                city=city if has_city else None,
                latitude=request.latitude if has_coords else None,
                longitude=request.longitude if has_coords else None,
            )
        except WeatherClientError as exc:
            location_label = city or "当前位置"
            data = {
                "city": city,
                "targetDate": target_date.isoformat(),
                "latitude": request.latitude if has_coords else None,
                "longitude": request.longitude if has_coords else None,
                "note": (
                    "Weather provider request failed. Do not invent exact "
                    "temperature, precipitation, or wind values."
                ),
            }
            result = AgentToolResult(
                status="failed",
                errorCode="WEATHER_PROVIDER_ERROR",
                retryable=True,
                messageForAgent=(
                    f"Weather fetch failed for {location_label}: {exc}. "
                    "Do not invent weather facts."
                ),
                messageForUser="实时天气服务暂时不可用，本次只根据你的文字需求判断穿搭约束。",
                data=data,
            )
            tools["get_weather"] = result
            return {"tools": tools, "weather_context": data}

        # ── forecast unavailable for this location / date ─────────────
        if forecast is None:
            location_label = city or "当前位置"
            data = {
                "city": city,
                "targetDate": target_date.isoformat(),
                "latitude": request.latitude if has_coords else None,
                "longitude": request.longitude if has_coords else None,
                "note": (
                    "Weather data is not available for this location or date. "
                    "Infer weather only from the user's message."
                ),
            }
            result = AgentToolResult(
                status="skipped",
                errorCode="WEATHER_NOT_AVAILABLE",
                retryable=False,
                messageForAgent=(
                    f"No forecast available for {location_label!r} on "
                    f"{target_date.isoformat()}. Do not invent weather facts."
                ),
                messageForUser=(
                    f"暂无{location_label} {target_date.isoformat()} 的天气数据。"
                ),
                data=data,
            )
            tools["get_weather"] = result
            return {"tools": tools, "weather_context": data}

        # ── success ───────────────────────────────────────────────────
        location_label = forecast.city or "当前位置"
        weather_context: dict[str, Any] = {
            "city": forecast.city,
            "targetDate": forecast.forecast_date.isoformat(),
            "temperatureMax": forecast.temperature_max,
            "temperatureMin": forecast.temperature_min,
            "weatherType": forecast.weather_type,
            "precipitation": forecast.precipitation,
            "windSpeed": forecast.wind_speed,
            "source": "open-meteo",
            "sourceType": forecast.source,
        }
        result = AgentToolResult(
            status="success",
            data=weather_context,
            messageForAgent=(
                f"Real weather for {location_label} on "
                f"{forecast.forecast_date.isoformat()}: "
                f"{forecast.weather_type}, "
                f"{forecast.temperature_min}°C–{forecast.temperature_max}°C, "
                f"precipitation {forecast.precipitation} mm. "
                "Use these facts to choose weather_type and weather_profile "
                "tags when searching wardrobe items."
            ),
            messageForUser=(
                f"{location_label} {forecast.forecast_date.isoformat()} 天气："
                f"{forecast.weather_type}，"
                f"{forecast.temperature_min}°C–{forecast.temperature_max}°C"
            ),
        )
        tools["get_weather"] = result
        print(f"Weather context: {weather_context}")
        return {"tools": tools, "weather_context": weather_context}

    def _get_clothing_taxonomy(self, state: OutfitAgentState) -> dict[str, Any]:
        """Loads controlled taxonomy values for the recommendation prompt.

        Args:
            state: Current LangGraph state.

        Returns:
            Partial state update containing taxonomy and tool result.
        """
        # The Agent should reason over backend-approved category and weather
        # vocabularies, not free-form values invented per request.
        taxonomy = get_clothing_taxonomy()
        result = AgentToolResult(
            status="success",
            data=taxonomy,
            messageForAgent=(
                "Use category as the clothing type. Use previewCategoryMapping "
                "only when a preview tool is called."
            ),
        )

        # Store taxonomy both as a tool result and as direct state so downstream
        # nodes do not need to unpack the tool payload every time.
        tools = dict(state.get("tools", {}))
        tools["get_clothing_taxonomy"] = result
        return {"tools": tools, "taxonomy": taxonomy}

    def _outfit_agent_loop(self, state: OutfitAgentState) -> dict[str, Any]:
        """Runs the LLM-controlled outfit recommendation tool loop.

        Args:
            state: Current LangGraph state with request, weather, and taxonomy.

        Returns:
            Partial state update containing recommendation, trace, and retrieved
            wardrobe candidates.
        """
        executor = OutfitAgentToolExecutor(
            db=state["db"],
            user_id=state["user_id"],
            request=state["request"],
            taxonomy=state.get("taxonomy", {}),
            clothing_payload_builder=self._clothing_item_payload,
        )
        messages = self._agent_loop_messages(state)
        tool_cache: dict[str, AgentToolResult] = dict(state.get("tool_cache", {}))
        tools_trace = dict(state.get("tools", {}))
        wardrobe_by_id: dict[str, dict[str, Any]] = {}
        final_content = ""
        call_index = 0

        try:
            for _ in range(MAX_TOOL_ROUNDS):
                assistant_message = self.llm.complete_message(
                    messages,
                    tools=executor.tool_schemas(),
                    tool_choice="auto",
                )
                tool_calls = assistant_message.get("tool_calls") or []

                # No tool calls means the model has decided to finish with a
                # final recommendation message.
                if not tool_calls:
                    final_content = _message_content_as_text(
                        assistant_message.get("content")
                    )
                    break

                messages.append(_assistant_message_for_history(assistant_message))
                for tool_call in tool_calls:
                    call_index += 1
                    result = executor.execute(
                        tool_name=_tool_call_name(tool_call),
                        raw_arguments=_tool_call_arguments(tool_call),
                        cache=tool_cache,
                    )
                    tools_trace[f"{_tool_call_name(tool_call)}#{call_index}"] = result
                    tools_trace[_tool_call_name(tool_call)] = result
                    _collect_wardrobe_items(wardrobe_by_id, result)
                    messages.append(_tool_result_message(tool_call, result))

            # If the model keeps calling tools until the budget is exhausted,
            # disable tools for one final response based on accumulated facts.
            if not final_content:
                messages.append(
                    {
                        "role": "user",
                        "content": (
                            "工具调用预算已经用完。不要再调用工具，只能基于已经返回的"
                            "衣柜工具结果输出最终 JSON。"
                        ),
                    }
                )
                final_message = self.llm.complete_message(messages)
                final_content = _message_content_as_text(final_message.get("content"))

            recommendation = _json_loads_object(final_content)
        except (AgentConfigurationError, AgentLLMError) as exc:
            recommendation = {
                "outfit": {"name": "推荐生成失败", "items": []},
                "recommendationReason": "LLM provider 调用失败。",
                "weatherReason": None,
                "preferenceReason": None,
                "missingItems": [],
                "userMessage": f"暂时无法生成穿搭推荐：{exc}",
                "error": str(exc),
            }
        except ValueError as exc:
            recommendation = {
                "outfit": {"name": "推荐解析失败", "items": []},
                "recommendationReason": "模型没有返回符合要求的 JSON。",
                "weatherReason": None,
                "preferenceReason": None,
                "missingItems": [],
                "userMessage": f"暂时无法解析穿搭推荐：{exc}",
                "error": str(exc),
            }

        # Normalize every model result before later nodes use it. This prevents
        # hallucinated clothing ids from reaching preview generation.
        wardrobe_items = list(wardrobe_by_id.values())
        recommendation = self._normalize_recommendation(
            recommendation,
            wardrobe_items,
        )
        return {
            "recommendation": recommendation,
            "wardrobe_items": wardrobe_items,
            "tool_cache": tool_cache,
            "tools": tools_trace,
        }

    def _agent_loop_messages(self, state: OutfitAgentState) -> list[dict[str, Any]]:
        """Builds the initial messages for the LLM tool loop.

        Args:
            state: Current LangGraph state.

        Returns:
            OpenAI-compatible message list for the recommendation loop.
        """
        taxonomy = state.get("taxonomy", {})
        prompt_payload = {
            "userRequest": state["request"].model_dump(mode="json", by_alias=True),
            "conversationContext": state.get("conversation_context", {}),
            "interpretedContext": state.get("interpreted_context", {}),
            "weatherContext": state.get("weather_context", {}),
            "taxonomy": {
                "category": taxonomy.get("category", []),
                "previewCategoryMapping": taxonomy.get("previewCategoryMapping", {}),
                "validTagValuesByKey": valid_tag_values_by_key(taxonomy),
            },
            "responseSchema": {
                "outfit": {
                    "name": "string",
                    "items": [
                        {
                            "clothingItemId": "string",
                            "slot": "top|bottom|shoes|outerwear|accessory",
                        }
                    ],
                },
                "recommendationReason": "string",
                "weatherReason": "string|null",
                "preferenceReason": "string|null",
                "missingItems": ["string"],
                "userMessage": "string",
            },
        }

        # The first system message is the behavioral contract. It tells the
        # model when to use tools and how to stop.
        return [
            {
                "role": "system",
                "content": (
                    "You are an outfit recommendation agent for an AI wardrobe "
                    "app. Use search_wardrobe_items when you need real wardrobe "
                    "items. Do not invent clothing ids. Recommend only clothing "
                    "ids returned by tools in this run. You may call the tool "
                    "multiple times for top, bottom, shoes, or outerwear. A complete "
                    "outfit normally needs top, bottom, and shoes; outerwear is "
                    "optional unless weather or user intent requires it. Do not "
                    "mark a slot as missing until you have searched that slot, "
                    "or searched broadly and confirmed no returned item can fill it. "
                    "If a needed slot is missing from the current tool results, call "
                    "search_wardrobe_items again with a broader or slot-specific "
                    "category before finalizing. Stop calling tools only after you "
                    "have enough returned items for the outfit or have evidence that "
                    "a slot is unavailable. Return a raw JSON object matching "
                    "responseSchema; do not wrap it in markdown fences. Do not put "
                    "per-item reasons inside outfit.items. Explain the whole outfit "
                    "once in recommendationReason, and explain weather only in "
                    "weatherReason. "
                    "Tags must use validTagValuesByKey. For rainy weather use "
                    "weather_type=rain or weather_profile values; never use a "
                    "tag key named weather."
                ),
            },
            {
                "role": "user",
                "content": _json_dumps(prompt_payload),
            },
        ]

    def _preview_branch(self, state: OutfitAgentState) -> Literal["preview", "final"]:
        """Chooses whether to enter the preview node.

        Args:
            state: Current LangGraph state.

        Returns:
            `"preview"` when preview generation was requested, otherwise
            `"final"`.
        """
        # This condition keeps the graph shape stable while allowing the first
        # API version to skip preview generation by default.
        return "preview" if state["request"].generate_preview else "final"

    def _generate_outfit_preview(self, state: OutfitAgentState) -> dict[str, Any]:
        """Builds the preview tool result for the current JSON-only endpoint.

        Args:
            state: Current LangGraph state.

        Returns:
            Partial state update containing a skipped preview result.
        """
        # The existing preview API requires multipart upload with a person image.
        # This Agent endpoint is JSON-only, so it reports a truthful skipped
        # state and still exposes which selected items could map to preview slots.
        result = AgentToolResult(
            status="skipped",
            errorCode="PERSON_IMAGE_REQUIRED",
            retryable=False,
            messageForAgent=(
                "The current outfit preview API requires a person image upload. "
                "This JSON-only agent endpoint cannot create that task yet."
            ),
            messageForUser="当前 Agent 接口还没有上传真人照片参数，所以暂不生成预览图。",
            data={
                "selectedPreviewItems": self._selected_preview_items(
                    state.get("recommendation", {}),
                    state.get("wardrobe_items", []),
                )
            },
        )

        # Keep preview output in the same tool-result format as other nodes so
        # the final response can present a consistent execution trace.
        tools = dict(state.get("tools", {}))
        tools["generate_outfit_preview"] = result
        return {"tools": tools, "preview": result}

    def _final_response(self, state: OutfitAgentState) -> dict[str, Any]:
        """Assembles the public API response payload.

        Args:
            state: Current LangGraph state.

        Returns:
            Partial state update with the final response payload.
        """
        recommendation = state.get("recommendation", {})

        # If preview was not requested, synthesize a skipped preview result so
        # clients can always read the same `preview` response field.
        preview = state.get("preview") or AgentToolResult(
            status="skipped",
            messageForAgent="Preview generation was not requested.",
            messageForUser="本次未请求生成预览图。",
            data={},
        )

        # Keep provider metadata and raw model output in the response during MVP
        # development. This makes it easier to inspect Agent behavior.
        final = {
            "conversationId": state.get("conversation_context", {}).get(
                "conversationId"
            ),
            "providerName": self.llm.provider_name,
            "providerModel": self.llm.model,
            "outfit": recommendation.get("outfit", {"name": "", "items": []}),
            "recommendationReason": recommendation.get("recommendationReason", ""),
            "weatherReason": recommendation.get("weatherReason"),
            "preferenceReason": recommendation.get("preferenceReason"),
            "missingItems": recommendation.get("missingItems") or [],
            "preview": preview,
            "tools": state.get("tools", {}),
            "rawModelOutput": recommendation,
        }
        return {"final": final}

    def _clothing_item_payload(self, db: Session, item: ClothingItem) -> dict[str, Any]:
        """Converts a clothing ORM object into the Agent prompt payload.

        Args:
            db: Database session used to look up a representative image.
            item: Clothing item ORM row.

        Returns:
            JSON-like clothing item summary safe to expose to the LLM.
        """
        # Keep the model-facing item summary small. Preview generation resolves
        # garment images from `id`, so image URLs and storage details are not
        # part of the search tool contract.
        return {
            "id": str(item.id),
            "name": item.name,
            "category": item.category,
            "previewGarmentCategory": CATEGORY_TO_PREVIEW_GARMENT_CATEGORY.get(
                item.category or ""
            ),
            "color": _first_tag_value(item.final_tags or [], "color"),
            "material": item.material,
            "style": item.style,
        }

    def _normalize_recommendation(
        self,
        recommendation: dict[str, Any],
        wardrobe_items: list[dict[str, Any]],
    ) -> dict[str, Any]:
        """Normalizes and validates an LLM recommendation.

        Args:
            recommendation: Raw model JSON object.
            wardrobe_items: Candidate items returned by wardrobe retrieval.

        Returns:
            Recommendation object with safe defaults and filtered outfit items.
        """
        # Build an allow-list from retrieval results. Any model-selected item id
        # outside this set is treated as hallucinated and removed.
        known_ids = {item["id"] for item in wardrobe_items}
        outfit = recommendation.get("outfit")

        # Guarantee the response has an outfit object even if the model returns
        # a malformed value or omits the field.
        if not isinstance(outfit, dict):
            outfit = {"name": "穿搭推荐", "items": []}

        # Keep only dictionary items that reference known clothing ids, and trim
        # each selected item back to the public response schema. Item-level
        # reasons are intentionally excluded; the model explains the outfit once
        # in `recommendationReason`.
        items = outfit.get("items") if isinstance(outfit.get("items"), list) else []
        normalized_items = []
        for item in items:
            if not isinstance(item, dict) or item.get("clothingItemId") not in known_ids:
                continue
            normalized_items.append(
                {
                    "clothingItemId": item.get("clothingItemId"),
                    "slot": item.get("slot"),
                }
            )
        outfit["items"] = normalized_items

        # Fill optional fields with stable defaults so FastAPI response
        # serialization does not depend on perfect model output.
        recommendation["outfit"] = outfit
        recommendation.setdefault("recommendationReason", "")
        recommendation.setdefault("weatherReason", None)
        recommendation.setdefault("preferenceReason", None)
        if not isinstance(recommendation.get("missingItems"), list):
            recommendation["missingItems"] = []
        return recommendation

    def _selected_preview_items(
        self,
        recommendation: dict[str, Any],
        wardrobe_items: list[dict[str, Any]],
    ) -> list[dict[str, Any]]:
        """Extracts selected items that can be passed to preview generation.

        Args:
            recommendation: Normalized recommendation object.
            wardrobe_items: Candidate wardrobe item payloads.

        Returns:
            A list of preview-compatible item/category pairs.
        """
        # Index candidates by id to map selected recommendation items back to
        # backend-approved preview garment categories.
        by_id = {item["id"]: item for item in wardrobe_items}
        selected = []

        # Ignore selected items that cannot map to TOP/BOTTOM/SHOES; they can
        # still be explained as accessories, but the current preview API cannot
        # render them.
        for item in recommendation.get("outfit", {}).get("items", []):
            clothing_id = item.get("clothingItemId")
            candidate = by_id.get(clothing_id)
            if not candidate or not candidate.get("previewGarmentCategory"):
                continue
            selected.append(
                {
                    "clothingItemId": clothing_id,
                    "garmentCategory": candidate["previewGarmentCategory"],
                }
            )
        return selected


def _first_tag_value(tags: list[dict[str, Any]], key: str) -> str | None:
    """Finds the first value for a tag key.

    Args:
        tags: List of `{key, value}` tag dictionaries.
        key: Tag key to find.

    Returns:
        The first matching tag value, or `None` when absent.
    """
    # final_tags are stored as a list of small objects, so a linear scan keeps
    # this helper simple and avoids assuming a unique key constraint.
    for tag in tags:
        if tag.get("key") == key:
            return tag.get("value")
    return None


def _request_context_from_explicit_fields(
    request: OutfitRecommendationRequest,
) -> dict[str, Any]:
    """Builds fallback interpreted context from explicit request fields.

    Args:
        request: Public outfit recommendation request.

    Returns:
        Interpreted context containing only trusted request fields.
    """
    # This fallback keeps the graph runnable when the extraction model is absent
    # in tests or temporarily fails in production.
    return {
        "intent": "new_outfit",
        "targetDate": request.target_date.isoformat() if request.target_date else None,
        "city": request.city,
        "weatherRequired": bool(
            request.city or request.latitude is not None or request.longitude is not None
        ),
        "occasion": None,
        "styleIntent": None,
        "carryOverPreviousOutfit": False,
        "revisionRequest": {
            "slot": None,
            "instruction": None,
        },
        "userConstraints": [],
    }


def _normalize_interpreted_context(
    raw_context: dict[str, Any],
    fallback_context: dict[str, Any],
) -> dict[str, Any]:
    """Normalizes LLM-extracted request context.

    Args:
        raw_context: JSON object returned by the request-understanding model.
        fallback_context: Explicit-field fallback context.

    Returns:
        Sanitized interpreted context with stable keys.
    """
    if not isinstance(raw_context, dict):
        raise ValueError("request understanding response must be a JSON object")

    # Explicit request values win over extracted values. This prevents the model
    # from overriding API-provided date/location fields with a weaker guess.
    target_date = fallback_context.get("targetDate") or raw_context.get("targetDate")
    city = fallback_context.get("city") or _optional_string(raw_context.get("city"))
    constraints = raw_context.get("userConstraints")
    if not isinstance(constraints, list):
        constraints = fallback_context.get("userConstraints", [])

    return {
        "intent": _allowed_string(
            raw_context.get("intent"),
            allowed={"new_outfit", "revise_outfit", "ask_question", "other"},
            default=fallback_context.get("intent") or "new_outfit",
        ),
        "targetDate": _valid_date_string(target_date),
        "city": city,
        "weatherRequired": _boolean_or_default(
            raw_context.get("weatherRequired"),
            bool(fallback_context.get("weatherRequired")),
        ),
        "occasion": _optional_string(raw_context.get("occasion")),
        "styleIntent": _optional_string(raw_context.get("styleIntent")),
        "carryOverPreviousOutfit": _boolean_or_default(
            raw_context.get("carryOverPreviousOutfit"),
            bool(fallback_context.get("carryOverPreviousOutfit")),
        ),
        "revisionRequest": _normalize_revision_request(
            raw_context.get("revisionRequest"),
        ),
        "userConstraints": [str(item) for item in constraints if item is not None],
    }


def _empty_conversation_context(user_id: UUID) -> dict[str, Any]:
    """Builds an empty conversation context for stateless runs.

    Args:
        user_id: Authenticated user identifier.

    Returns:
        Empty conversation context.
    """
    return {
        "conversationId": f"user:{user_id}",
        "recentTurns": [],
        "lastRecommendation": None,
    }


def _normalize_revision_request(raw_revision: Any) -> dict[str, str | None]:
    """Normalizes a revision request extracted from user text.

    Args:
        raw_revision: Candidate revision object from the model.

    Returns:
        Stable revision request payload.
    """
    if not isinstance(raw_revision, dict):
        return {"slot": None, "instruction": None}
    return {
        "slot": _allowed_string(
            raw_revision.get("slot"),
            allowed={"top", "bottom", "shoes", "outerwear", "accessory"},
            default=None,
        ),
        "instruction": _optional_string(raw_revision.get("instruction")),
    }


def _allowed_string(
    value: Any,
    *,
    allowed: set[str],
    default: str | None,
) -> str | None:
    """Normalizes a string against an allow-list.

    Args:
        value: Candidate string value.
        allowed: Accepted values.
        default: Fallback value.

    Returns:
        Accepted value or fallback.
    """
    normalized = _optional_string(value)
    if normalized in allowed:
        return normalized
    return default


def _parse_interpreted_date(raw_date: Any) -> date | None:
    """Parses an interpreted ISO date.

    Args:
        raw_date: Date value from interpreted context.

    Returns:
        Parsed date, or None when absent/invalid.
    """
    if not isinstance(raw_date, str) or not raw_date.strip():
        return None
    try:
        return date.fromisoformat(raw_date.strip())
    except ValueError:
        return None


def _valid_date_string(raw_date: Any) -> str | None:
    """Validates that a value is an ISO date string.

    Args:
        raw_date: Candidate date value.

    Returns:
        ISO date string or None.
    """
    parsed = _parse_interpreted_date(raw_date)
    return parsed.isoformat() if parsed else None


def _optional_string(value: Any) -> str | None:
    """Normalizes optional string values from model output.

    Args:
        value: Candidate string value.

    Returns:
        Stripped string, or None when empty/not a string.
    """
    if not isinstance(value, str):
        return None
    stripped = value.strip()
    return stripped or None


def _boolean_or_default(value: Any, default: bool) -> bool:
    """Normalizes optional boolean values from model output.

    Args:
        value: Candidate boolean value.
        default: Fallback value when candidate is not a boolean.

    Returns:
        Boolean value.
    """
    return value if isinstance(value, bool) else default


def _assistant_message_for_history(message: dict[str, Any]) -> dict[str, Any]:
    """Normalizes an assistant message before appending tool results.

    Args:
        message: Assistant message returned by the provider.

    Returns:
        Message object suitable for the next OpenAI-compatible request.
    """
    normalized = {
        "role": "assistant",
        "content": message.get("content"),
    }

    # Tool result messages must follow the exact assistant `tool_calls` that
    # caused them, including provider-generated ids.
    if message.get("tool_calls"):
        normalized["tool_calls"] = message["tool_calls"]
    return normalized


def _tool_result_message(
    tool_call: dict[str, Any],
    result: AgentToolResult,
) -> dict[str, Any]:
    """Builds an OpenAI-compatible tool result message.

    Args:
        tool_call: Provider tool call object.
        result: Backend tool execution result.

    Returns:
        `role=tool` message to append to the model conversation.
    """
    return {
        "role": "tool",
        "tool_call_id": tool_call.get("id"),
        "name": _tool_call_name(tool_call),
        "content": result.model_dump_json(by_alias=True),
    }


def _tool_call_name(tool_call: dict[str, Any]) -> str:
    """Extracts the function name from a provider tool call.

    Args:
        tool_call: Provider tool call object.

    Returns:
        Function name, or an empty string when missing.
    """
    return str(tool_call.get("function", {}).get("name") or "")


def _tool_call_arguments(tool_call: dict[str, Any]) -> str | dict[str, Any] | None:
    """Extracts raw function arguments from a provider tool call.

    Args:
        tool_call: Provider tool call object.

    Returns:
        Raw arguments string or object.
    """
    return tool_call.get("function", {}).get("arguments")


def _collect_wardrobe_items(
    wardrobe_by_id: dict[str, dict[str, Any]],
    result: AgentToolResult,
) -> None:
    """Adds successful tool-returned wardrobe items into an id index.

    Args:
        wardrobe_by_id: Mutable index of retrieved wardrobe items.
        result: Tool result that may contain wardrobe items.
    """
    if result.status != "success" or not result.data:
        return

    # Later validation uses this allow-list to remove hallucinated ids from the
    # model's final recommendation.
    for item in result.data.get("items", []):
        if isinstance(item, dict) and item.get("id"):
            wardrobe_by_id[item["id"]] = item


def _message_content_as_text(content: Any) -> str:
    """Converts provider message content into text.

    Args:
        content: Provider-specific message content.

    Returns:
        String content.
    """
    if isinstance(content, list):
        return "".join(
            part.get("text", "") if isinstance(part, dict) else str(part)
            for part in content
        )
    return "" if content is None else str(content)


def _json_loads_object(raw: str) -> dict[str, Any]:
    """Parses a JSON object from model response text.

    Args:
        raw: Raw assistant response text.

    Returns:
        Parsed JSON object.

    Raises:
        ValueError: If no JSON object can be parsed.
    """
    text = raw.strip()
    try:
        parsed = json.loads(text)
    except json.JSONDecodeError:
        # Providers sometimes wrap JSON in markdown or a short explanation.
        # Extract the outermost object so the Agent can still continue.
        start = text.find("{")
        end = text.rfind("}")
        if start < 0 or end <= start:
            raise ValueError("LLM response did not contain a JSON object")
        parsed = json.loads(text[start:end + 1])

    if not isinstance(parsed, dict):
        raise ValueError("LLM response JSON must be an object")
    return parsed


def _json_dumps(payload: dict[str, Any]) -> str:
    """Serializes prompt payloads while preserving Chinese text.

    Args:
        payload: Structured prompt payload.

    Returns:
        JSON string suitable for inclusion in a chat message.
    """
    import json

    # `ensure_ascii=False` keeps Chinese user requests readable in model logs
    # and provider traces.
    return json.dumps(payload, ensure_ascii=False, default=str)
