from typing import Any, Literal, TypedDict
from uuid import UUID

from langgraph.graph import END, START, StateGraph
from sqlalchemy import or_
from sqlalchemy.orm import Session

from app.models.clothing_item import ClothingItem, Image
from app.models.wardrobe import WardrobeItem
from app.schemas.agent import AgentToolResult, OutfitRecommendationRequest
from app.services.agent_llm_service import (
    AgentConfigurationError,
    AgentLLMError,
    OpenAICompatibleChatClient,
)
from app.services.clothing_taxonomy import (
    CATEGORY_TO_PREVIEW_GARMENT_CATEGORY,
    get_clothing_taxonomy,
)


class OutfitAgentState(TypedDict, total=False):
    """Shared state passed between LangGraph outfit recommendation nodes."""

    db: Session
    user_id: UUID
    request: OutfitRecommendationRequest
    tools: dict[str, AgentToolResult]
    taxonomy: dict[str, Any]
    weather_context: dict[str, Any]
    wardrobe_items: list[dict[str, Any]]
    recommendation: dict[str, Any]
    preview: AgentToolResult
    final: dict[str, Any]


class OutfitRecommendationAgent:
    """LangGraph workflow for outfit recommendation.

    The workflow is intentionally controlled instead of being a fully open
    ReAct loop. Business-critical tool ordering stays deterministic, while the
    LLM is used for the recommendation decision itself.
    """

    def __init__(self, llm: OpenAICompatibleChatClient | None = None) -> None:
        """Initializes the Agent and compiles its LangGraph workflow.

        Args:
            llm: Optional chat client override used by tests or alternate
                OpenAI-compatible providers.
        """
        self.llm = llm or OpenAICompatibleChatClient()
        self.graph = self._build_graph()

    def run(
        self,
        db: Session,
        *,
        user_id: UUID,
        request: OutfitRecommendationRequest,
    ) -> dict[str, Any]:
        """Runs the outfit Agent for one authenticated user request.

        Args:
            db: Database session used by tool nodes.
            user_id: Authenticated user identifier.
            request: User request and optional retrieval filters.

        Returns:
            Final structured recommendation payload.

        Raises:
            AgentConfigurationError: If the LLM provider configuration is
                missing before the graph starts.
        """
        self.llm.ensure_configured()

        # Seed the graph state with backend-only objects. These are never
        # generated by the model, which keeps tool execution trusted.
        final_state = self.graph.invoke(
            {
                "db": db,
                "user_id": user_id,
                "request": request,
                "tools": {},
            }
        )
        return final_state["final"]

    def _build_graph(self):
        """Builds the controlled LangGraph recommendation workflow.

        Returns:
            A compiled LangGraph workflow ready to invoke.
        """
        # Register every business tool as a graph node. This makes the product
        # flow explicit: weather context, taxonomy, wardrobe retrieval, model
        # decision, optional preview, then final API response.
        workflow = StateGraph(OutfitAgentState)
        workflow.add_node("get_weather", self._get_weather)
        workflow.add_node("get_clothing_taxonomy", self._get_clothing_taxonomy)
        workflow.add_node("search_wardrobe_items", self._search_wardrobe_items)
        workflow.add_node("compose_outfit", self._compose_outfit)
        workflow.add_node("generate_outfit_preview", self._generate_outfit_preview)
        workflow.add_node("final_response", self._final_response)

        workflow.add_edge(START, "get_weather")
        workflow.add_edge("get_weather", "get_clothing_taxonomy")
        workflow.add_edge("get_clothing_taxonomy", "search_wardrobe_items")
        workflow.add_edge("search_wardrobe_items", "compose_outfit")

        # Preview is conditional because the first JSON-only endpoint cannot
        # upload a person image. The graph still models the node so later work
        # can connect the real preview API without reshaping the workflow.
        workflow.add_conditional_edges(
            "compose_outfit",
            self._preview_branch,
            {
                "preview": "generate_outfit_preview",
                "final": "final_response",
            },
        )
        workflow.add_edge("generate_outfit_preview", "final_response")
        workflow.add_edge("final_response", END)
        return workflow.compile()

    def _get_weather(self, state: OutfitAgentState) -> dict[str, Any]:
        """Adds weather context to the graph state.

        Args:
            state: Current LangGraph state.

        Returns:
            Partial state update containing weather context and tool result.
        """
        request = state["request"]

        # Weather is a placeholder in the first Agent version. The important
        # behavior is explicit degradation: the model is told not to invent
        # exact weather facts when no provider has been called.
        data = {
            "city": request.city,
            "targetDate": request.target_date.isoformat()
            if request.target_date else None,
            "note": (
                "Weather provider is not connected yet. Infer weather only from "
                "the user's message, city, and date if present."
            ),
        }
        result = AgentToolResult(
            status="skipped",
            errorCode="WEATHER_PROVIDER_NOT_CONFIGURED",
            retryable=False,
            messageForAgent=(
                "No external weather facts are available. Do not invent exact "
                "temperature, precipitation, or wind values."
            ),
            messageForUser="暂未接入实时天气服务，本次只根据你的文字需求判断穿搭约束。",
            data=data,
        )

        # Tool results are accumulated for debugging, final response metadata,
        # and future failure-recovery logic.
        tools = dict(state.get("tools", {}))
        tools["get_weather"] = result
        return {"tools": tools, "weather_context": data}

    def _get_clothing_taxonomy(self, state: OutfitAgentState) -> dict[str, Any]:
        """Loads controlled taxonomy values for the recommendation prompt.

        Args:
            state: Current LangGraph state.

        Returns:
            Partial state update containing taxonomy and tool result.
        """
        # The Agent should reason over backend-approved category and weather
        # vocabularies, not free-form values invented per request.
        taxonomy = get_clothing_taxonomy()
        result = AgentToolResult(
            status="success",
            data=taxonomy,
            messageForAgent=(
                "Use category as the clothing type. Use previewCategoryMapping "
                "only when a preview tool is called."
            ),
        )

        # Store taxonomy both as a tool result and as direct state so downstream
        # nodes do not need to unpack the tool payload every time.
        tools = dict(state.get("tools", {}))
        tools["get_clothing_taxonomy"] = result
        return {"tools": tools, "taxonomy": taxonomy}

    def _search_wardrobe_items(self, state: OutfitAgentState) -> dict[str, Any]:
        """Retrieves wardrobe candidates available to the Agent.

        Args:
            state: Current LangGraph state.

        Returns:
            Partial state update containing candidate wardrobe items.
        """
        request = state["request"]
        db = state["db"]

        # Start with the security boundary: only the authenticated user's
        # non-deleted clothing items may be considered.
        q = db.query(ClothingItem).filter(
            ClothingItem.user_id == state["user_id"],
            ClothingItem.deleted_at.is_(None),
        )

        # Optional source filtering supports owned/imported separation without
        # exposing the unrelated wardrobe `type` field to the Agent.
        if request.source is not None:
            q = q.filter(ClothingItem.source == request.source)

        # Wardrobe filtering uses the junction table, because wardrobes are
        # containers and do not duplicate clothing item data.
        if request.wardrobe_id is not None:
            q = q.join(
                WardrobeItem,
                WardrobeItem.clothing_item_id == ClothingItem.id,
            ).filter(WardrobeItem.wardrobe_id == request.wardrobe_id)

        # Agent tool input intentionally exposes only structured final_tags, not
        # free-text query. This keeps retrieval grounded in confirmed metadata.
        if request.tags:
            for tag in request.tags:
                q = q.filter(
                    ClothingItem.final_tags.contains(
                        [{"key": tag.key, "value": tag.value}]
                    )
                )

        # Convert ORM rows into compact JSON-like payloads before they enter
        # the model prompt. The LLM never sees SQLAlchemy objects.
        items = q.order_by(ClothingItem.created_at.desc()).limit(request.limit).all()
        payload = [self._clothing_item_payload(db, item) for item in items]
        status: Literal["success", "failed"] = "success"
        result = AgentToolResult(
            status=status,
            data={"items": payload, "total": len(payload)},
            messageForAgent=(
                "These are the only wardrobe items available to recommend from. "
                "If a needed slot is missing, say so instead of inventing an item."
            ),
        )

        # Store retrieval output in the graph trace and direct state so the
        # compose node can use the candidates without another database query.
        tools = dict(state.get("tools", {}))
        tools["search_wardrobe_items"] = result
        return {"tools": tools, "wardrobe_items": payload}

    def _compose_outfit(self, state: OutfitAgentState) -> dict[str, Any]:
        """Asks the LLM to compose an outfit from retrieved candidates.

        Args:
            state: Current LangGraph state with weather, taxonomy, and wardrobe
                candidates.

        Returns:
            Partial state update containing the normalized recommendation.
        """
        request = state["request"]

        # The prompt payload is deliberately structured. This gives the model
        # enough context for judgment while making it easy to validate the
        # returned clothing ids against the retrieval result.
        prompt_payload = {
            "userRequest": request.model_dump(mode="json", by_alias=True),
            "weatherContext": state.get("weather_context", {}),
            "taxonomy": state.get("taxonomy", {}),
            "wardrobeItems": state.get("wardrobe_items", []),
        }

        # The system prompt defines a strict JSON contract and explicitly bans
        # recommending items that were not returned by the wardrobe tool.
        messages = [
            {
                "role": "system",
                "content": (
                    "You are an outfit recommendation agent for an AI wardrobe app. "
                    "Return only a JSON object. Do not recommend wardrobe items that "
                    "are not present in wardrobeItems. If a category is missing, add "
                    "it to missingItems. The JSON schema is: "
                    "{outfit:{name:string,items:[{clothingItemId:string,slot:string,"
                    "reason:string}]},recommendationReason:string,weatherReason:string,"
                    "preferenceReason:string|null,missingItems:string[],userMessage:string}."
                ),
            },
            {
                "role": "user",
                "content": _json_dumps(prompt_payload),
            },
        ]

        # LLM failures are degraded into a structured recommendation failure
        # instead of crashing the whole graph after the route has already
        # entered the business workflow.
        try:
            recommendation = self.llm.complete_json(messages)
        except (AgentConfigurationError, AgentLLMError) as exc:
            recommendation = {
                "outfit": {"name": "推荐生成失败", "items": []},
                "recommendationReason": "LLM provider 调用失败。",
                "weatherReason": None,
                "preferenceReason": None,
                "missingItems": [],
                "userMessage": f"暂时无法生成穿搭推荐：{exc}",
                "error": str(exc),
            }

        # Normalize every model result before later nodes use it. This prevents
        # hallucinated clothing ids from reaching preview generation.
        recommendation = self._normalize_recommendation(
            recommendation,
            state.get("wardrobe_items", []),
        )
        return {"recommendation": recommendation}

    def _preview_branch(self, state: OutfitAgentState) -> Literal["preview", "final"]:
        """Chooses whether to enter the preview node.

        Args:
            state: Current LangGraph state.

        Returns:
            `"preview"` when preview generation was requested, otherwise
            `"final"`.
        """
        # This condition keeps the graph shape stable while allowing the first
        # API version to skip preview generation by default.
        return "preview" if state["request"].generate_preview else "final"

    def _generate_outfit_preview(self, state: OutfitAgentState) -> dict[str, Any]:
        """Builds the preview tool result for the current JSON-only endpoint.

        Args:
            state: Current LangGraph state.

        Returns:
            Partial state update containing a skipped preview result.
        """
        # The existing preview API requires multipart upload with a person image.
        # This Agent endpoint is JSON-only, so it reports a truthful skipped
        # state and still exposes which selected items could map to preview slots.
        result = AgentToolResult(
            status="skipped",
            errorCode="PERSON_IMAGE_REQUIRED",
            retryable=False,
            messageForAgent=(
                "The current outfit preview API requires a person image upload. "
                "This JSON-only agent endpoint cannot create that task yet."
            ),
            messageForUser="当前 Agent 接口还没有上传真人照片参数，所以暂不生成预览图。",
            data={
                "selectedPreviewItems": self._selected_preview_items(
                    state.get("recommendation", {}),
                    state.get("wardrobe_items", []),
                )
            },
        )

        # Keep preview output in the same tool-result format as other nodes so
        # the final response can present a consistent execution trace.
        tools = dict(state.get("tools", {}))
        tools["generate_outfit_preview"] = result
        return {"tools": tools, "preview": result}

    def _final_response(self, state: OutfitAgentState) -> dict[str, Any]:
        """Assembles the public API response payload.

        Args:
            state: Current LangGraph state.

        Returns:
            Partial state update with the final response payload.
        """
        recommendation = state.get("recommendation", {})

        # If preview was not requested, synthesize a skipped preview result so
        # clients can always read the same `preview` response field.
        preview = state.get("preview") or AgentToolResult(
            status="skipped",
            messageForAgent="Preview generation was not requested.",
            messageForUser="本次未请求生成预览图。",
            data={},
        )

        # Keep provider metadata and raw model output in the response during MVP
        # development. This makes it easier to inspect Agent behavior.
        final = {
            "providerName": self.llm.provider_name,
            "providerModel": self.llm.model,
            "outfit": recommendation.get("outfit", {"name": "", "items": []}),
            "recommendationReason": recommendation.get("recommendationReason", ""),
            "weatherReason": recommendation.get("weatherReason"),
            "preferenceReason": recommendation.get("preferenceReason"),
            "missingItems": recommendation.get("missingItems") or [],
            "preview": preview,
            "tools": state.get("tools", {}),
            "rawModelOutput": recommendation,
        }
        return {"final": final}

    def _clothing_item_payload(self, db: Session, item: ClothingItem) -> dict[str, Any]:
        """Converts a clothing ORM object into the Agent prompt payload.

        Args:
            db: Database session used to look up a representative image.
            item: Clothing item ORM row.

        Returns:
            JSON-like clothing item summary safe to expose to the LLM.
        """
        # Pick one display image for the Agent/client response. The query favors
        # processed/front images where available, while still falling back to
        # original/back images.
        image = (
            db.query(Image)
            .filter(
                Image.clothing_item_id == item.id,
                or_(
                    Image.image_type == "PROCESSED_FRONT",
                    Image.image_type == "ORIGINAL_FRONT",
                    Image.image_type == "PROCESSED_BACK",
                    Image.image_type == "ORIGINAL_BACK",
                ),
            )
            .order_by(Image.image_type.desc())
            .first()
        )

        # Translate the database image type into the existing file route kind.
        image_url = None
        if image is not None:
            kind = {
                "PROCESSED_FRONT": "processed-front",
                "ORIGINAL_FRONT": "original-front",
                "PROCESSED_BACK": "processed-back",
                "ORIGINAL_BACK": "original-back",
            }[image.image_type]
            image_url = f"/files/clothing-items/{item.id}/{kind}"

        # The payload distinguishes source category from preview garment slot so
        # the model can reason over clothing type while preview tooling receives
        # only supported TOP/BOTTOM/SHOES slots.
        return {
            "id": str(item.id),
            "name": item.name,
            "category": item.category,
            "previewGarmentCategory": CATEGORY_TO_PREVIEW_GARMENT_CATEGORY.get(
                item.category or ""
            ),
            "color": _first_tag_value(item.final_tags or [], "color"),
            "material": item.material,
            "style": item.style,
            "source": item.source,
            "imageUrl": image_url,
            "finalTags": item.final_tags or [],
            "customTags": item.custom_tags or [],
        }

    def _normalize_recommendation(
        self,
        recommendation: dict[str, Any],
        wardrobe_items: list[dict[str, Any]],
    ) -> dict[str, Any]:
        """Normalizes and validates an LLM recommendation.

        Args:
            recommendation: Raw model JSON object.
            wardrobe_items: Candidate items returned by wardrobe retrieval.

        Returns:
            Recommendation object with safe defaults and filtered outfit items.
        """
        # Build an allow-list from retrieval results. Any model-selected item id
        # outside this set is treated as hallucinated and removed.
        known_ids = {item["id"] for item in wardrobe_items}
        outfit = recommendation.get("outfit")

        # Guarantee the response has an outfit object even if the model returns
        # a malformed value or omits the field.
        if not isinstance(outfit, dict):
            outfit = {"name": "穿搭推荐", "items": []}

        # Keep only dictionary items that reference known clothing ids. This is
        # the main guardrail between LLM output and backend tool execution.
        items = outfit.get("items") if isinstance(outfit.get("items"), list) else []
        outfit["items"] = [
            item for item in items
            if isinstance(item, dict) and item.get("clothingItemId") in known_ids
        ]

        # Fill optional fields with stable defaults so FastAPI response
        # serialization does not depend on perfect model output.
        recommendation["outfit"] = outfit
        recommendation.setdefault("recommendationReason", "")
        recommendation.setdefault("weatherReason", None)
        recommendation.setdefault("preferenceReason", None)
        if not isinstance(recommendation.get("missingItems"), list):
            recommendation["missingItems"] = []
        return recommendation

    def _selected_preview_items(
        self,
        recommendation: dict[str, Any],
        wardrobe_items: list[dict[str, Any]],
    ) -> list[dict[str, Any]]:
        """Extracts selected items that can be passed to preview generation.

        Args:
            recommendation: Normalized recommendation object.
            wardrobe_items: Candidate wardrobe item payloads.

        Returns:
            A list of preview-compatible item/category pairs.
        """
        # Index candidates by id to map selected recommendation items back to
        # backend-approved preview garment categories.
        by_id = {item["id"]: item for item in wardrobe_items}
        selected = []

        # Ignore selected items that cannot map to TOP/BOTTOM/SHOES; they can
        # still be explained as accessories, but the current preview API cannot
        # render them.
        for item in recommendation.get("outfit", {}).get("items", []):
            clothing_id = item.get("clothingItemId")
            candidate = by_id.get(clothing_id)
            if not candidate or not candidate.get("previewGarmentCategory"):
                continue
            selected.append(
                {
                    "clothingItemId": clothing_id,
                    "garmentCategory": candidate["previewGarmentCategory"],
                }
            )
        return selected


def _first_tag_value(tags: list[dict[str, Any]], key: str) -> str | None:
    """Finds the first value for a tag key.

    Args:
        tags: List of `{key, value}` tag dictionaries.
        key: Tag key to find.

    Returns:
        The first matching tag value, or `None` when absent.
    """
    # final_tags are stored as a list of small objects, so a linear scan keeps
    # this helper simple and avoids assuming a unique key constraint.
    for tag in tags:
        if tag.get("key") == key:
            return tag.get("value")
    return None


def _json_dumps(payload: dict[str, Any]) -> str:
    """Serializes prompt payloads while preserving Chinese text.

    Args:
        payload: Structured prompt payload.

    Returns:
        JSON string suitable for inclusion in a chat message.
    """
    import json

    # `ensure_ascii=False` keeps Chinese user requests readable in model logs
    # and provider traces.
    return json.dumps(payload, ensure_ascii=False, default=str)
